seed: 231102

data:
  target: datasets.mnist.MNIST
  params:
    root: ~/data/MNIST/
    img_size: 32
    split: train

dataloader:
  num_workers: 4
  pin_memory: true
  prefetch_factor: 2

model:
  target: models.autoencoder.AutoEncoder
  params:
    img_channels: 1
    dim: 64
    dim_mults: [1, 2, 4]
    with_bn: true
    with_tanh: true
    init_type: normal

train:
  n_steps: 10000
  batch_size: 512
  resume: ~

  noise_type: fft
  noise_stats: ./freq_stats/freq_stats_mnist32.pt

  loss_type: l2
  coef_rec: 1.0
  coef_idem: 1.0
  coef_tight: 0.1
  tight_clamp_ratio: ~

  print_freq: 100
  sample_freq: 500
  save_freq: 10000
  n_samples: 64

  optim:
    target: torch.optim.Adam
    params:
      lr: 0.0001
      betas: [0.5, 0.999]
